### ISSUE TITLE
dtanderson/factorio moved to factoriotools/factorio

### ISSUE THREAD

**Issue by Tetricz** [ich777/docker-templates#3]
https://github.com/ich777/docker-templates/blob/d51bb9b8e26a95d5b72c0132e9897897413316e4/ich777/Factorio.xml#L4

dtanderson has stopped updating and there were issues pushing to the previous docker repo.

Until you change that the docker repo, it won't be fully up to date.

**Comment by ich777** [comment]
@Tetricz thank you, changed the template
