### ISSUE TITLE
Terraria 1.4.0.2 issue

### ISSUE THREAD

**Issue by jkluch** [ich777/docker-templates#6]
Hey, I used this to setup a new 1.4.0.1 server but when 1.4.0.2 came out my unraid docker image didn't show an update.  I had to manually append `:latest` to the existing xml to get the new image with the 1.4.0.2 fix.
https://github.com/ich777/docker-templates/blob/5aa272ab60386d2cba48178f02658a0aa7b0d947/ich777/Terraria.xml#L4

**Comment by ich777** [comment]
That should be no problem, since Unraid will always pull the latest build if you set it to nothing, have you tried to force an update?
